#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2015-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import io
import json
import math
import shutil
import sys

import yaml

1 or 0 @ 0  # Python >= 3.5 is required

ap = argparse.ArgumentParser()
ap.add_argument('-j', '--json-input', action='store_true', help='parse input as JSON')
ap.add_argument('path', metavar='FILE', nargs='?', help='YAML file to parse')
options = ap.parse_args()
tsize = shutil.get_terminal_size(fallback=(math.inf, math.inf))
if options.path is not None:
    fp = open(options.path, 'rb')
else:
    fp = sys.stdin.buffer
with fp:
    if options.json_input:
        if sys.version_info < (3, 6):
            fp = io.TextIOWrapper(fp, encoding='UTF-8')
        d = json.load(fp)
    else:
        d = yaml.safe_load(fp)
yaml.dump(d,
    stream=sys.stdout.buffer,
    sort_keys=False,
    allow_unicode=True,
    encoding='UTF-8',
    width=(tsize.columns - 6),
)

# vim:ts=4 sts=4 sw=4 et
