name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python-version: '3.6'
          os: ubuntu-18.04
        - python-version: '3.7'
          os: ubuntu-20.04
        - python-version: '3.8'
          os: ubuntu-20.04
        - python-version: '3.9'
          os: ubuntu-20.04
        - python-version: '3.10'
          os: ubuntu-22.04
        - python-version: '3.11'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: set up pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{matrix.os}}-python${{matrix.python-version}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install wheel
      run:
        python3 -m pip install wheel
    - name: install PyYAML
      run: |
        sudo apt-get install libyaml-dev
        python3 -m pip install --verbose pyyaml
    - name: smoke test
      run:
        prove -v
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
